_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
aa:
    value: null
amp:
    value: false
amp_dtype:
    value: float16
amp_impl:
    value: native
aug_repeats:
    value: 0
aug_splits:
    value: 0
batch_size:
    value: 256
bce_loss:
    value: false
bce_pos_weight:
    value: null
bce_sum:
    value: false
bce_target_thresh:
    value: null
bn_eps:
    value: null
bn_momentum:
    value: null
channels_last:
    value: false
checkpoint_hist:
    value: 10
class_map:
    value: ""
clip_grad:
    value: null
clip_mode:
    value: norm
color_jitter:
    value: 0.4
color_jitter_prob:
    value: null
cooldown_epochs:
    value: 0
crop_pct:
    value: null
cutmix:
    value: 1
cutmix_minmax:
    value: null
data:
    value: null
data_dir:
    value: /home/beomjun/data/cifar10
dataset:
    value: torch/cifar10
dataset_download:
    value: true
dataset_trust_remote_code:
    value: false
decay_epochs:
    value: 90
decay_milestones:
    value:
        - 90
        - 180
        - 270
decay_rate:
    value: 0.1
device:
    value: cuda:0
device_modules:
    value: null
dist_bn:
    value: reduce
distributed:
    value: true
drop:
    value: 0
drop_block:
    value: null
drop_connect:
    value: null
drop_path:
    value: 0.1
epoch_repeats:
    value: 0
epochs:
    value: 300
eval_metric:
    value: top1
experiment:
    value: CIFAR10
fast_norm:
    value: false
fuser:
    value: ""
gaussian_blur_prob:
    value: null
gp:
    value: null
grad_accum_steps:
    value: 1
grad_checkpointing:
    value: false
grayscale_prob:
    value: null
head_init_bias:
    value: null
head_init_scale:
    value: null
hflip:
    value: 0.5
img_size:
    value: 224
in_chans:
    value: null
initial_checkpoint:
    value: ""
input_img_mode:
    value: null
input_key:
    value: null
input_size:
    value: null
interpolation:
    value: ""
jsd_loss:
    value: false
layer_decay:
    value: null
learning_rate:
    value: 0.0001
local_rank:
    value: 0
log_interval:
    value: 1
log_wandb:
    value: true
lr:
    value: 0.0001
lr_base:
    value: 0.1
lr_base_scale:
    value: ""
lr_base_size:
    value: 256
lr_cycle_decay:
    value: 0.5
lr_cycle_limit:
    value: 1
lr_cycle_mul:
    value: 1
lr_k_decay:
    value: 1
lr_noise:
    value: null
lr_noise_pct:
    value: 0.67
lr_noise_std:
    value: 1
mean:
    value:
        - 0.4914
        - 0.4822
        - 0.4465
min_lr:
    value: 0
mixup:
    value: 0.8
mixup_mode:
    value: batch
mixup_off_epoch:
    value: 0
mixup_prob:
    value: 1
mixup_switch_prob:
    value: 0.5
model:
    value: vit_tiny_patch16_224
model_ema:
    value: false
model_ema_decay:
    value: 0.9998
model_ema_force_cpu:
    value: false
model_ema_warmup:
    value: false
momentum:
    value: 0.9
no_aug:
    value: false
no_ddp_bb:
    value: false
no_prefetcher:
    value: false
no_resume_opt:
    value: false
num_classes:
    value: 10
opt:
    value: adamw
opt_betas:
    value: null
opt_eps:
    value: null
output:
    value: ./output/vit_tiny_patch16_224_lr0.0001
patience_epochs:
    value: 10
pin_mem:
    value: false
prefetcher:
    value: true
pretrained:
    value: false
pretrained_path:
    value: null
rank:
    value: 0
ratio:
    value:
        - 0.75
        - 1.3333333333333333
recount:
    value: 1
recovery_interval:
    value: 0
remode:
    value: pixel
reprob:
    value: 0
resplit:
    value: false
resume:
    value: ""
save_images:
    value: false
scale:
    value:
        - 0.08
        - 1
sched:
    value: cosine
sched_on_updates:
    value: false
seed:
    value: 1234
smoothing:
    value: 0.1
split_bn:
    value: false
start_epoch:
    value: null
std:
    value:
        - 0.2023
        - 0.1994
        - 0.201
sync_bn:
    value: false
synchronize_step:
    value: false
target_key:
    value: null
torchcompile:
    value: null
torchcompile_mode:
    value: null
torchscript:
    value: false
train_crop_mode:
    value: null
train_interpolation:
    value: random
train_num_samples:
    value: null
train_split:
    value: train
tta:
    value: 0
use_multi_epochs_loader:
    value: false
val_num_samples:
    value: null
val_split:
    value: validation
validation_batch_size:
    value: null
vflip:
    value: 0
wandb_resume_id:
    value: ""
wandb_tags:
    value: []
warmup_epochs:
    value: 10
warmup_lr:
    value: 1e-05
warmup_prefix:
    value: false
weight_decay:
    value: 0.1
worker_seeding:
    value: all
workers:
    value: 4
world_size:
    value: 8
